"""add user filter data

Revision ID: 7966243b33b0
Revises: 76c55e9571a3
Create Date: 2026-07-11 15:18:00.186545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7966243b33b0'
down_revision: Union[str, Sequence[str], None] = '76c55e9571a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_filter_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('brightness', sa.Float(), nullable=False),
    sa.Column('vibrance', sa.Float(), nullable=False),
    sa.Column('highlights_shadows', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('tint', sa.Float(), nullable=False),
    sa.Column('duotone', sa.Float(), nullable=False),
    sa.Column('duotone_dark', sa.String(length=7), nullable=False),
    sa.Column('duotone_light', sa.String(length=7), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id')
    )
    op.create_index(op.f('ix_user_filter_data_id'), 'user_filter_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_filter_data_id'), table_name='user_filter_data')
    op.drop_table('user_filter_data')
    # ### end Alembic commands ###
